version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - "8002:8000"
  
  dynamodb-init:
    image: amazon/aws-cli
    depends_on:
      dynamodb-local:
        condition: service_started  
    environment:
      AWS_ACCESS_KEY_ID:      dummy
      AWS_SECRET_ACCESS_KEY:  dummy
      AWS_DEFAULT_REGION:     eu-west-1 
    entrypoint:
      [
        "sh","-c",
        "aws dynamodb create-table \
           --table-name TimeSlots \
           --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=slotId,AttributeType=S \
           --key-schema AttributeName=userId,KeyType=HASH AttributeName=slotId,KeyType=RANGE \
           --billing-mode PAY_PER_REQUEST \
           --endpoint-url http://dynamodb-local:8000 \
           --region eu-west-1 \
         || echo 'Table already exists'"
      ]

  auth-service:
    build:
      context: .  
      dockerfile: app/auth/Dockerfile
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./test.db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  slots-service:
    build:
      context: .
      dockerfile: app/slots/Dockerfile
    volumes:
      - .:/app
    environment:
      AWS_ACCESS_KEY_ID:      dummy
      AWS_SECRET_ACCESS_KEY:  dummy
      AWS_REGION: eu-west-1
      SLOTS_TABLE: TimeSlots
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      dynamodb-init:
        condition: service_started    
    ports:
      - "8001:8001"
